const { EleventyServerless } = require("@11ty/eleventy");
const functions = require("firebase-functions");

// Explicit dependencies for the bundler from config file and global data.
// The file is generated by the Eleventy Serverless Bundler Plugin.
require("./eleventy-bundler-modules.js");


exports.dynamic_fb = functions.https.onRequest(async (request, response) => {
  let elev = new EleventyServerless("dynamic_fb", {
    path: request.url,
    query: request.query,
    functionsDir: "./dynamic_fb",
  });

  try {
    let [page] = await elev.getOutput();
  } catch (error) {
    // Only console log for matching serverless paths
    // (otherwise you’ll see a bunch of BrowserSync 404s for non-dynamic URLs during --serve)
    // if (elev.isServerlessUrl(event.path)) {
      console.log("Serverless Error:", error);
    // }
  }

  response.send("Hello from Firebase!");
});
